; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ch32v
board = genericCH32V203C8T6
framework = noneos-sdk
upload_protocol = wch-link
monitor_speed = 115200
board_build.ldscript = ldscripts/Link_CH32V20x_hotfix.ld

[env:genericCH32V203C8T6]

[env:autobench_cve2024_2212]
build_flags = -DAPP_AUTOBENCH_TARGET=0 -DAPP_AUTOBENCH_COMPARE

[env:autobench_cve2025_1674]
build_flags = -DAPP_AUTOBENCH_TARGET=1 -DAPP_AUTOBENCH_COMPARE

[env:autobench_cve2025_12899]
build_flags = -DAPP_AUTOBENCH_TARGET=2 -DAPP_AUTOBENCH_COMPARE
